config/routes.rb
CohoopRails::Application.routes.draw do
  authenticated :user do
    root :to => "feeds#filter", via: :post, as: :feed_filtered
    root :to => "feeds#show"
    match '/:feed_type' => 'feeds#filter', via: :post, constraints: { feed_type: /community|tags/ }, as: :feed_filtered_by_type
    match '/:feed_type' => 'feeds#show', constraints: { feed_type: /community|tags/ }, as: :feed
  end

  root to: 'landing#welcome'
  get '/how' => 'landing#how', as: :landing_how
  get '/who' => 'landing#who', as: :landing_who
  get '/where' => 'landing#where', as: :landing_where
  get '/agree' => 'landing#agree', as: :landing_agree
  get '/final' => 'landing#final', as: :landing_final

  match '/mailslist/create' => 'mails_list#create', via: :post

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  resources  :users, :only => [:index, :show, :update] do
    resources :microhoops, only: [:create]
  end

  post '/microhoops/:id/vote_up' => 'microhoops#vote_up', constraints: { id: /\d+/ }, as: :microhoop_vote_up

  profile_constraints = { id: /\d+/, first: /[a-zA-Z]+/, last: /[a-zA-Z]+/ }
  match '/:id/:first-:last/' => 'users#show', constraints: profile_constraints , as: :profile

  match '/:id/:first-:last/documents' => 'users_documents#show', constraints: profile_constraints , as: :user_documents
  match '/:id/:first-:last/documents/new' => 'users_documents#new', constraints: profile_constraints , as: :new_user_documents
  match '/:id/:first-:last/documents/create' => 'users_documents#create', constraints: profile_constraints , as: :create_user_documents

  match '/hoop/:id' => 'documents#show', as: :documents

  resources :relationships,            only: [:create, :destroy]
  resources :users_tags_relationships, only: [:create, :destroy]

  resources :tags, only: [:show] do
    get :autocomplete_tag_name, on: :collection, as: :autocomplete
  end

end

app/models/feed.rb
class Feed
  delegate :avatar, :name, to: :user
  attr_reader :filters, :filter, :user

  def initialize(user, page)
    @user = user
    @page = page

    @filters = [:all, :urgent, :microhoops, :activities]
    @filter  = :all
  end

  def filter=(symbol)
    # TODO: Cumulable filters
    symbol = symbol.to_sym
    raise ArgumentError, "#{symbol} filter does not exists" unless @filters.include? symbol
    @filter = symbol
  end

  ## Must be overloaded by subclasses ##
  def type
    raise NotImplementedError, "#type method is not implemented for #{self.class}"
  end

  def microhoops
    raise NotImplementedError, "#microhoops method is not implemented for #{self.class}"
  end

  def microhoops_with_priority(opts = { urgent: false })
    urgent = opts[:urgent]
    self.microhoops.where('urgent = ?', urgent)
  end

  def activities
    raise NotImplementedError, "#activities method is not implemented for #{self.class}"
    # TODO: Implement Activities
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user!, only: [:show]

  def show
    @title  = 'News'
    generate_feed
  end

  def filter
    generate_feed
    @feed.filter = params[:feed][:filter].to_sym
    @presenter = UserFeedPresenter.new(@feed, view_context)
    respond_with(@feed) do |f|
      f.js
    end
  end

  private
    def generate_feed
      page = params[:page] || 1
      type = params[:feed_type] || :community
      # TODO: Switch to microhoops & activities when activities are implemented
      @user = UserFeedInterface.new(current_user)
      @feed = @user.build_feed(page, type)
    end
end

app/views/feeds/_filter.html.erb
<li>
  <%= form_tag(feed_filtered_by_type_path(feed_type: feed_type), class: 'filter-form', remote: true) do %>
    <%= hidden_field :feed, :filter, value: filter %>
    <%= submit_tag filter.to_s.humanize, class: 'btn btn-info' %>
  <% end %>
</li>

app/views/feeds/_filter.js.erb
$('#microhoops-list .microhoops').replaceWith("<%= j @presenter.feed_content %>");

app/views/feeds/_microhoop.html.erb
<li class="microhoop<%= microhoop.urgent ? ' urgent' : '' %>" id="microhoop-<%= microhoop.id %>">
  <div class="microhoop-infos">
    <div class="microhoop-avatar">
      <%= user.avatar %>
    </div>
    <div class="microhoop-vote">
      <%= form_tag(microhoop_vote_up_path(id: microhoop.id), remote: true) do |f| %>
        <%= submit_tag 'Vote this microhoop up', class: 'btn-vote' %>
      <% end %>
      <span class="count">
        <%= microhoop.vote_count %>
      </span>
    </div>
  </div> <!-- .infos -->
  <div class="microhoop-metadata">
    <span class="microhoop-username"><%= link_to user.name, profile_path(id: user.id, first:user.first_name.downcase, last: user.last_name.downcase) %></span>
    <div class="microhoop-urgent">
      This microhoop is urgent !
    </div>
  </div> <!-- .metadata -->

  <div class="microhoop-content">
    <%= microhoop.content %>
  </div>

  <div class="microhoop-date">
    <em><%= time_ago_in_words(microhoop.created_at) %> ago</em>
  </div>

</li>

app/views/feeds/filter.js.erb
$('#microhoops-list .pagination').remove();
$('#microhoops-list .microhoops').replaceWith("<%= j @presenter.feed_content %>");

app/views/feeds/show.html.erb
<% present @feed, presenters: [:user, :feed] do |presenter| %>
  <div id="sidebar-left" class="span4 sidebar">
    <a href="<%= presenter.current_user_profile_link  %>" title="Go to your profile page" id="user-pinfos">
      <div class="avatar image-placeholder">
        <%= presenter.avatar(:huge) %>
      </div> <!-- .avatar -->
      <div class="username">
        <%= presenter.name %>
      </div>
    </a>
    <div id="filters">
      <h3>Filters</h3>
      <%= presenter.filters %>
    </div>
  <div id="list-users">
    <h3>User list</h3>
    <%= presenter.list_all_users %>
  </div>
  </div>
  <div id="feed-content" class="span8">
    <div class="tabs">
      <%= presenter.feed_type %>
    </div>
    <div id="add-microhoop-form" class="post-microhoop">
      <h3>Post a microhoop</h3>
      <%= presenter.add_microhoop_form %>
    </div>
    <div id="microhoops-list">
      <h3><%= presenter.feed_title %></h3>
      <%= presenter.feed_content %>
    </div>
  </div>
 <% end %>