config/routes.rb
CohoopRails::Application.routes.draw do
  authenticated :user do
    root :to => "feeds#filter", via: :post, as: :feed_filtered
    root :to => "feeds#show"
    match '/:feed_type' => 'feeds#filter', via: :post, constraints: { feed_type: /community|tags/ }, as: :feed_filtered_by_type
    match '/:feed_type' => 'feeds#show', constraints: { feed_type: /community|tags/ }, as: :feed
  end

  root to: 'landing#welcome'
  get '/how' => 'landing#how', as: :landing_how
  get '/who' => 'landing#who', as: :landing_who
  get '/where' => 'landing#where', as: :landing_where
  get '/agree' => 'landing#agree', as: :landing_agree
  get '/final' => 'landing#final', as: :landing_final

  match '/mailslist/create' => 'mails_list#create', via: :post

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  resources  :users, :only => [:index, :show, :update] do
    resources :microhoops, only: [:create]
  end

  post '/microhoops/:id/vote_up' => 'microhoops#vote_up', constraints: { id: /\d+/ }, as: :microhoop_vote_up

  profile_constraints = { id: /\d+/, first: /[a-zA-Z]+/, last: /[a-zA-Z]+/ }
  match '/:id/:first-:last/' => 'users#show', constraints: profile_constraints , as: :profile

  match '/:id/:first-:last/documents' => 'users_documents#show', constraints: profile_constraints , as: :user_documents
  match '/:id/:first-:last/documents/new' => 'users_documents#new', constraints: profile_constraints , as: :new_user_documents
  match '/:id/:first-:last/documents/create' => 'users_documents#create', constraints: profile_constraints , as: :create_user_documents

  match '/hoop/:id' => 'documents#show', as: :documents

  resources :relationships,            only: [:create, :destroy]
  resources :users_tags_relationships, only: [:create, :destroy]

  resources :tags, only: [:show] do
    get :autocomplete_tag_name, on: :collection, as: :autocomplete
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  layout 'home'

  def welcome
    @pagination = 1
  end

  def how
    @pagination = 2
  end

  def who
    @pagination = 3
  end

  def where
    @pagination = 4
  end

  def agree
    @pagination = 5
  end

  def final
    @pagination = 6
    @mail = MailingListMail.new
  end
end

app/views/landing/agree.html.erb
<h2>DO YOU AGREE THAT STUDYING ALONE SUCKS?</h2>

<div class="form">
  <div class="question">
    <%= link_to 'Yes', landing_final_path , class: 'radio' %>
  </div>
  <div class="dots big-dots"></div>
  <div class="question">
    <%= link_to 'Yes', landing_final_path , class: 'radio' %>
  </div>
</div>

app/views/landing/final.html.erb
<h2 class="final">WHO ARE WE?</h2>
<h3>COHOOP IS A SOCIAL LEARNING NETWORK</h3>
<p>An online platform for students to connect over shared interests or challenges and learn with a community.</p>

<p id="loop">
  <strong>SO GET INTO THE LOOP !</strong><br />Send us your email to get an invite
</p>
<!-- form here -->
<%= form_for(@mail, url: mailslist_create_path, remote: true, html: { class: 'form final-form' }) do |f| %>
  <%= f.email_field :mail, class: 'input-mail', required: true %>
  <%= f.submit "OK", class: 'form-submit' %>
<% end %>

app/views/landing/how.html.erb
<h2>HOW DO YOU USUALLY STUDY?</h2>

<!-- form here -->
<div class="form">
  <div class="question">
    <%= link_to 'Alone', landing_who_path, class: 'radio' %>
  </div>
  <div class="dots big-dots"></div>
  <div class="question">
    <%= link_to 'Group', landing_who_path, class: 'radio' %>
  </div>
</div>
<!-- form here -->

app/views/landing/welcome.html.erb
<h2>Welcome !</h2>
<p>Find out who we are !</p>
<%= link_to 'Start' , landing_how_path %>

app/views/landing/where.html.erb
<h2>WHERE DO YOU STUDY?</h2>

<!-- form here -->
<div class="form">
  <div class="question">
    <%= link_to 'Library', landing_agree_path , class: 'radio' %>
  </div>
  <div class="dots small-dots"></div>
  <div class="question">
    <%= link_to 'Café', landing_agree_path , class: 'radio' %>
  </div>
  <div class="dots small-dots"></div>
  <div class="question">
    <%= link_to 'Home', landing_agree_path , class: 'radio' %>
  </div>
</div>
<!-- form here -->

app/views/landing/who.html.erb
<h2>WHO ANSWERS YOUR QUESTIONS?</h2>

<!-- form here -->
<div class="form">
  <div class="question">
    <%= link_to 'Google', landing_where_path , class: 'radio' %>
  </div>
  <div class="dots small-dots"></div>
  <div class="question">
    <%= link_to 'Peers', landing_where_path , class: 'radio' %>
  </div>
  <div class="dots small-dots"></div>
  <div class="question">
    <%= link_to 'Teacher', landing_where_path , class: 'radio' %>
  </div>
</div>