config/routes.rb
CohoopRails::Application.routes.draw do
  authenticated :user do
    root :to => "feeds#filter", via: :post, as: :feed_filtered
    root :to => "feeds#show"
    match '/:feed_type' => 'feeds#filter', via: :post, constraints: { feed_type: /community|tags/ }, as: :feed_filtered_by_type
    match '/:feed_type' => 'feeds#show', constraints: { feed_type: /community|tags/ }, as: :feed
  end

  root to: 'landing#welcome'
  get '/how' => 'landing#how', as: :landing_how
  get '/who' => 'landing#who', as: :landing_who
  get '/where' => 'landing#where', as: :landing_where
  get '/agree' => 'landing#agree', as: :landing_agree
  get '/final' => 'landing#final', as: :landing_final

  match '/mailslist/create' => 'mails_list#create', via: :post

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  resources  :users, :only => [:index, :show, :update] do
    resources :microhoops, only: [:create]
  end

  post '/microhoops/:id/vote_up' => 'microhoops#vote_up', constraints: { id: /\d+/ }, as: :microhoop_vote_up

  profile_constraints = { id: /\d+/, first: /[a-zA-Z]+/, last: /[a-zA-Z]+/ }
  match '/:id/:first-:last/' => 'users#show', constraints: profile_constraints , as: :profile

  match '/:id/:first-:last/documents' => 'users_documents#show', constraints: profile_constraints , as: :user_documents
  match '/:id/:first-:last/documents/new' => 'users_documents#new', constraints: profile_constraints , as: :new_user_documents
  match '/:id/:first-:last/documents/create' => 'users_documents#create', constraints: profile_constraints , as: :create_user_documents

  match '/hoop/:id' => 'documents#show', as: :documents

  resources :relationships,            only: [:create, :destroy]
  resources :users_tags_relationships, only: [:create, :destroy]

  resources :tags, only: [:show] do
    get :autocomplete_tag_name, on: :collection, as: :autocomplete
  end

end

app/controllers/users_documents_controller.rb
class UsersDocumentsController < ApplicationController
  before_filter :authenticate_user!, only: [:update, :create, :new]

  def show
    @user     = get_user_through_params || return

    ether     = EtherpadLite.connect('http://docs.cohoop.com', 'Hxo0L3mVABqNCAsGl8cEZEXCajIxMYa0')
    ep_groups = ether.client.ListPadsOfAuthor(authorID: 'a.' + @user.id.to_s)

    user_groups = @user.groups
    ap(ep_groups)
    ap(user_groups)

    @group = user_groups
    @document = Document.new();

    @title    = 'Documents'
  end

  def new
    @user     = get_user_through_params || return
  end

  def create
    @user     = get_user_through_params || return

    group     = Group.new()
    group.create_slug(@user)

    doc_name  = params[:document][:name]
    document  = Document.new(name: doc_name)
    document.create_slug

    if document.valid? && group.valid?
      # TODO: Refactor
      ether = EtherpadLite.connect('http://docs.cohoop.com', 'Hxo0L3mVABqNCAsGl8cEZEXCajIxMYa0')
      ether.create_group mapper: group.slug

      document.groups_relationships.build(document_id: document.id)
      document.save

      @user.groups_relationships.build(group_id: group.id)
      @user.save
      redirect_to documents_path(id: document.slug)
    else
      respond_to do |format|
        format.js
      end
    end
  end
end

app/views/users_documents/_create_document_form.html.erb
<%= form_for document, url: create_user_documents_path(id: @user.id, first: @user.first_name.downcase, last: @user.last_name.downcase), html: { id: 'document-creation-form' } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit 'Create a new document', class: 'btn btn-cohoop' %>
<% end %>

app/views/users_documents/show.html.erb
<div id="main-content" class="row">
  <div class="span12">
    <h2>Manage your documents</h2>
    <% if @user.can_edit? %>
    <p><%= link_to 'Add a document', new_user_documents_path(id: @user.id, first: @user.first_name, last: @user.last_name), id: 'add-document', class: 'btn btn-cohoop' %></p>
    <div class="modal hide" id="new-document-popin">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Create a document</h3>
      </div>
      <div class="modal-body">
        <%= render partial: 'create_document_form', locals: { document: @document } %>
      </div>
    </div> <!-- #upload-popin -->
    <% end %>

    <table id="list-documents" class="table table-hover">
      <thead>
        <tr>
          <th><input type="checkbox" name="document_action" /></th>
          <th>Title</th>
          <th>Owner</th>
          <th>Last modified</th>
        </tr>
      </thead>
      <tbody>
        <% @user.documents.each do |document| %>
        <tr>
          <td><input type="checkbox" name="document_action" /></td>
          <td><%= link_to document.name, documents_path(id: document.slug) %></td>
          <td></td>
          <td></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>